Loading conda_R/4.0.x
here() starts at /users/mkaras/_PROJECTS/upstrap_manuscript
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.3     ✔ purrr   0.3.4
✔ tibble  3.1.1     ✔ dplyr   1.0.5
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Attaching package: ‘matrixStats’

The following object is masked from ‘package:dplyr’:

    count

Warning message:
In dir.create(path = res_fdir_agg) :
  '/users/mkaras/_PROJECTS/upstrap_manuscript/numerical_experiments/results_CL_shared/2021-06-08-lm_trt_agg' already exists
Starting PART 1...
100
200
300
400
500
600
700
800
900
1000
100
200
300
400
500
600
700
800
900
1000
100
200
300
400
500
600
700
800
900
1000
100
200
300
400
500
600
700
800
900
1000
100
200
300
400
500
600
700
800
900
1000
100
200
300
400
500
600
700
800
900
1000
100
200
300
400
500
600
700
800
900
1000
100
200
300
400
500
600
700
800
900
1000
Saved the results.
